services:
    auth-db:
        image: mysql:8.0
        container_name: auth-db
        volumes:
            - auth-db:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - auth-network
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_DATABASE: 'auth'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'secret'
    auth:
        image: auth-microservice:latest
        container_name: auth
        working_dir: /var/www
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/api
        networks:
            - auth-network
        depends_on:
            - auth-db
        environment:
            USER_ID: "${USER_ID}"
            GROUP_ID: "${GROUP_ID}"
            APP_ENV: "local"
    auth-frontend:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        user: "${USER_ID}:${GROUP_ID}"
        environment:
            USER_ID: "${USER_ID}"
            GROUP_ID: "${GROUP_ID}"
        container_name: auth-frontend
        volumes:
            - ./resources/frontend:/app
        ports:
            - "4200:4200"

volumes:
    auth-db:
        driver: local

networks:
    auth-network:
        driver: bridge
