version: "3"

services:
    auth-db:
        image: mysql:8.0
        container_name: auth-db
        volumes:
            - auth-db:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - auth-network
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_DATABASE: 'auth'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'secret'
    auth-db-testing:
        image: mysql:8.0
        container_name: auth-db-testing
        ports:
            - "3307:3306"
        networks:
            - auth-network
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_DATABASE: 'auth_testing'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'secret'
    auth-webserver:
        image: nginx:1.22-alpine
        container_name: auth-webserver
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/development/nginx:/etc/nginx/conf.d
        ports:
            - "8000:80"
        networks:
            - auth-network
        depends_on:
            - auth-php
    auth-php:
        build:
            context: .
            dockerfile: docker/development/php8.2/Dockerfile
        user: "${USER_ID}:${GROUP_ID}"
        container_name: auth-php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - auth-network
        depends_on:
            - auth-db
            - auth-db-testing

volumes:
    auth-db:
        driver: local

networks:
    auth-network:
        driver: bridge
