name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  tests:
    uses: Tomi0/auth-microservice/.github/workflows/tests.yml@main
  build:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag tomi0/auth-microservice:latest
      - name: Push the Docker image
        env:
          docker_token: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u tomi0 -p "$docker_token" && docker push tomi0/auth-microservice:latest
