name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: "Hola Mundo"
        run: sleep 2 && echo "Hola Mundo"
  hola-mundo1:
    runs-on: ubuntu-latest
    needs: [hola-mundo]
    steps:
      - name: "Hola Mundo1"
        run: sleep 2 && echo "Hola Mundo1"
  hola-mundo2:
    runs-on: ubuntu-latest
    needs: [hola-mundo]
    steps:
      - name: "Hola Mundo2"
        run: sleep 2 && echo "Hola Mundo2"
#  laravel-tests:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#        with:
#          php-version: '8.2'
#      - uses: actions/checkout@v3
#      - name: Copy .env
#        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#      - name: Install Dependencies
#        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#      - name: Generate key
#        run: php artisan key:generate
#      - name: Directory Permissions
#        run: chmod -R 777 storage bootstrap/cache
#      - name: Execute tests via PHPUnit
#        run: php artisan test
